[package]
name = "soroswap-library"
version = "2.0.0"
description = "Library that enables efficient and optimized code execution across different contracts on the Soroswap.Finance protocol"
homepage = "https://github.com/soroswap/core/tree/main/contracts/library"
repository = "https://github.com/soroswap/core/tree/main/contracts/library"
authors = ["esteblock <esteblock@paltalabs.io>"]
readme = "README.md"
license = "GPL-3.0"
edition = "2021"
keywords = ["no_std", "wasm", "soroswap", "amm", "soroban"]
publish = true 

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }
num-integer = { workspace=true, default-features = false, features = ["i128"] }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
