version: '3'
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all


  check:
    cmd: cargo check

  build:
    cmds:
      - task -d ../token build || exit 1
      - task -d ../liquidity_pool_plane build || exit 1
      - task -d ../locker_feed build || exit 1
      - soroban contract build --package aqua-soroban-liquidity-pool-contract
      - soroban contract optimize --wasm ../../bytecodes/aqua_liquidity_pool_contract.wasm --wasm-out ../../bytecodes/aqua_liquidity_pool_contract.wasm
      - le -l ../../bytecodes/*.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    deps:
      - build
    cmd: cargo test --features=slow_tests

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
