[package]
name        = "hoops-adapter-interface"
version     = "0.1.0"
edition     = { workspace = true }
publish     = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk  = { workspace = true }
hoops-common = { path = "../common" }
