[package]
name    = "hoops-account"
version = "0.1.0"
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk  = { workspace = true }
hoops-common = { path = "../common" }
