[package]
name = "upgrade"
version.workspace = true
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
access_control = { path = "../access_control" }
utils = { path = "../utils" }
