[package]
name = "aqua-upgrade"
version.workspace = true
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
aqua_access_control = { path = "../access_control" }
aqua-utils = { path = "../utils" }
