version: '3'
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - soroban contract build --package locker-feed
      - soroban contract optimize --wasm ../../bytecodes/locker_feed.wasm --wasm-out ../../bytecodes/aqua_locker_feed_contract.wasm
      - rm ../bytecodes/locker_feed.wasm
      - le -l ../../bytecodes/*.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
